# Generated by Django 2.0 on 2017-12-18 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="parent_task",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="todo.Task"
            ),
        ),
    ]
