# Generated by Django 2.0 on 2017-12-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_auto_20171218_2046"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="description",
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
