# Generated by Django 2.0 on 2017-12-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0007_task_is_done"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
