# Generated by Django 2.0 on 2018-02-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0024_todolist_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
