# Generated by Django 4.0.4 on 2022-05-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0030_task_todo_task_parent__f0e23a_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['parent_list_id'], name='todo_task_parent__02f2f8_idx'),
        ),
    ]
