# Generated by Django 5.0.2 on 2024-05-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0032_alter_task_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="rejected",
            field=models.BooleanField(default=False),
        ),
    ]
