# Generated by Django 5.0.2 on 2024-10-19 07:45

from django.conf import settings
from django.db import migrations, models


def reset_tasks_no(apps, schema_editor):
    Task = apps.get_model("todo", "Task")
    TodoList = apps.get_model("todo", "TodoList")

    lists_ids = TodoList.objects.values_list("id", flat=True)

    for list_id in lists_ids:
        tasks = Task.objects.filter(parent_list_id=list_id).order_by("creation_date")

        for idx, task in enumerate(tasks):
            # enumerate is zero based, we need to increment by one
            task.task_no = idx + 1

        Task.objects.bulk_update(tasks, ["task_no"])


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0033_task_rejected"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(reset_tasks_no, reset_tasks_no),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                fields=("parent_list_id", "task_no"), name="unique_task_no_in_list"
            ),
        ),
    ]
