[tool.poetry]
name = "yatdlm"
version = "0.1.0"
description = ""
authors = ["Kaci Adjou <adjou.kaci@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
django = "3.0.2"
psycopg2-binary = "^2.8.5"
virtualenv = "^20.0.25"

[tool.poetry.dev-dependencies]
ipython = "^7.16.1"
pylint = "^2.5.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
